export class Card{
    id:number;
    rupees:number;
    paisa:number;
    street:string;
    state:string;
    city:string;
    country:string;
    pincode:number;   
    phone:number;
    buyer_fname:string;
    buyer_lname:string;
    p1:number;
    p2:number;
    p3:number;
    p4:number;
    p5:number;
    p6:number;
    p7:number;
    p8:number;
    p9:number;
    p10:number;
}